{{- if .Values.agent.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8r-agent.fullname" . }}
  labels:
    {{- include "c8r-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.agent.configMap.content }}
  config.yaml: |- {{- (tpl .Values.agent.configMap.content .) | nindent 4 }}
  {{- else }}
  config.yaml: |- {{- .Files.Get "config/example.yaml" | trim | nindent 4 }}
  {{- end }}
{{- end }}
