{{- /*
ConfigMap for c8r-network-agent server configuration
*/ -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8r.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "c8r.labels" . | nindent 4 }}
data:
  config.yaml: |
    metrics_port: {{ .Values.metrics.port }}
    grpc_port: {{ .Values.service.port }}
    environment: {{ .Values.environment | quote }}
    cloud: {{ .Values.cloud | quote }}
    region: {{ .Values.region | quote }}
    cluster: {{ .Values.cluster | quote }}
    max_grpc_connection_age: {{ .Values.maxGRPCConnectionAge | quote }}
    num_exporter_workers: {{ .Values.exporter.numWorkers }}
    {{- if .Values.exporter.ignoreUDP }}
    ignore_udp: {{ .Values.exporter.ignoreUDP }}
    {{- end }}
    {{- if and .Values.exporter.azureContainerURL (not .Values.exporter.azureContainerURLFromEnv) }}
    azure_container_url: {{ .Values.exporter.azureContainerURL | quote }}
    {{- end }}
