{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "c8r.fullname" . }}-agent
  labels:
    {{- include "c8r.labels" . | nindent 4 }}
    {{- include "c8r.agentSelectorLabels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "c8r.agentSelectorLabels" . | nindent 6 }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "c8r.fullname" . }}-server
  labels:
    {{- include "c8r.labels" . | nindent 4 }}
    {{- include "c8r.serverSelectorLabels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "c8r.serverSelectorLabels" . | nindent 6 }}
{{- end }}
