{{- /*
PriorityClass for c8r-network-agent
Ensures agent and server pods are scheduled with appropriate priority
*/ -}}
{{- if .Values.priorityClass.enabled -}}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "c8r.priorityClassName" . }}
  labels:
    {{- include "c8r.labels" . | nindent 4 }}
description: {{ .Values.priorityClass.description | default "Priority class for c8r-network-agent to ensure pods are scheduled" | quote }}
globalDefault: false
preemptionPolicy: {{ .Values.priorityClass.preemptionPolicy }}
value: {{ .Values.priorityClass.value | int }}
{{- end }}
