apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c8r.fullname" . }}-clickhouse-credentials
  labels:
    {{- include "c8r.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.inserter.username | b64enc }}
  password: {{ .Values.inserter.password | b64enc }}
