apiVersion: v1
kind: Service
metadata:
  name: {{ include "c8r.fullname" . }}-server
  labels:
    {{- include "c8r.labels" . | nindent 4 }}
    {{- include "c8r.serverSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "c8r.serverSelectorLabels" . | nindent 4 }}
