apiVersion: v1
kind: Service
metadata:
  name: {{ (.Values.licenseProxy.service.name | default (printf "%s-license-proxy" .Release.Name)) }}
  namespace: {{ include "namespace" . }}
  labels:
  {{- include "labelsLicenseProxy" . | nindent 4 }}
  {{- if .Values.licenseProxy.service.labels }}
    {{- toYaml .Values.licenseProxy.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.licenseProxy.service.annotations }}
  annotations:
    {{- toYaml .Values.licenseProxy.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and (eq .Values.licenseProxy.service.type "LoadBalancer") .Values.licenseProxy.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.licenseProxy.service.externalTrafficPolicy | default "Cluster" }}
  {{- end }}
  internalTrafficPolicy: {{ .Values.licenseProxy.service.internalTrafficPolicy | default "Cluster" }}
  selector:
    app: {{ (.Values.licenseProxy.name | default (printf "%s-license-proxy" .Release.Name)) }}
  ports:
    - port: {{ .Values.licenseProxy.service.serverPort | default 8443  }}
      targetPort: {{ .Values.licenseProxy.serverPort | default 8443  }}
      protocol: "TCP"
      name: primary
    - port: {{ .Values.licenseProxy.service.statusPort | default  8080 }}
      targetPort: {{ .Values.licenseProxy.statusPort | default  8080 }}
      protocol: "TCP"
      name: status
  type: {{ .Values.licenseProxy.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.licenseProxy.service.type "LoadBalancer") .Values.licenseProxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.licenseProxy.service.loadBalancerIP }}
  {{- end }}
{{/*
*/}}

{{- if eq .Values.engine.mode "deployment" | required "Engine mode is required: engine.mode=deplyoment/sidecar" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ (.Values.api.service.name | default (printf "%s-api" .Release.Name)) }}
  namespace: {{ include "namespace" . }}
  labels:
  {{- include "labelsApi" . | nindent 4 }}
  {{- if .Values.api.service.labels }}
    {{- toYaml .Values.api.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
  {{- end }}
spec:
  internalTrafficPolicy: {{ .Values.api.service.internalTrafficPolicy | default "Cluster" }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy | default "Cluster" }}
  {{- end }}
  selector:
    app: {{ (.Values.api.name | default (printf "%s-api" .Release.Name)) }}
  ports:
    - port: {{ .Values.api.service.serverPort | default 8080  }}
      targetPort: {{ .Values.api.serverPort | default 8080 }}
      protocol: "TCP"
      name: primary
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.service.loadBalancerIP }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ (.Values.engine.service.name | default (printf "%s-engine" .Release.Name)) }}
  namespace: {{ include "namespace" . }}
  labels:
  {{- include "labelsEngine" . | nindent 4 }}
  {{- if .Values.engine.service.labels }}
    {{- toYaml .Values.engine.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.engine.service.annotations }}
  annotations:
    {{- toYaml .Values.engine.service.annotations | nindent 4 }}
  {{- end }}
spec:
  internalTrafficPolicy: {{ .Values.engine.service.internalTrafficPolicy | default "Cluster" }}
  {{- if and (eq .Values.engine.service.type "LoadBalancer") .Values.engine.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.engine.service.externalTrafficPolicy | default "Cluster" }}
  {{- end }}
  selector:
    app: {{ (.Values.engine.name | default (printf "%s-engine" .Release.Name)) }}
  ports:
    - port: {{ .Values.engine.service.serverPort | default 9090  }}
      targetPort: {{ .Values.engine.serverPort | default 9090 }}
      protocol: "TCP"
      name: primary
    - port: {{ .Values.engine.service.metricsPort | default 9991  }}
      targetPort: {{ .Values.engine.metricsPort | default 9991 }}
      protocol: "TCP"
      name: metrics
  type: {{ .Values.engine.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.engine.service.type "LoadBalancer") .Values.engine.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.engine.service.loadBalancerIP }}
  {{- end }}
{{- end -}}
{{/*
*/}}
