{{- if eq .Values.engine.mode "sidecar" | required "Engine mode is required: engine.mode=deplyoment/sidecar" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ (.Values.api.service.name | default (printf "%s-engine-api" .Release.Name)) }}
  namespace: {{ include "namespace" . }}
  labels:
  {{- include "labelsSidecar" . | nindent 4 }}
  {{- if .Values.api.service.labels }}
    {{- toYaml .Values.api.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
  {{- end }}
spec:
  internalTrafficPolicy: {{ .Values.api.service.internalTrafficPolicy | default "Cluster" }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy | default "Cluster" }}
  selector:
    app: {{ (.Values.api.name | default (printf "%s-engine-api" .Release.Name)) }}
  ports:
    - port: {{ .Values.api.service.serverPort | default 8080  }}
      targetPort: {{ .Values.api.serverPort | default 8080 }}
      protocol: "TCP"
      name: api
    - port: {{ .Values.engine.serverPort | default 9090  }}
      targetPort: {{ .Values.engine.serverPort | default 9090 }}
      protocol: "TCP"
      name: engine
    - port: {{ .Values.engine.metricsPort | default 9991  }}
      targetPort: {{ .Values.engine.metricsPort | default 9991 }}
      protocol: "TCP"
      name: engine-metrics
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.service.loadBalancerIP }}
  {{- end }}
{{- end -}}
{{/*
*/}}
