{{- if .Values.externalSecrets.create }}
  {{- if not .Values.externalSecrets.spec }}
    {{- fail "externalSecrets.spec is required." }}
  {{- end }}

apiVersion: {{ .Values.externalSecrets.apiVersion | default "external-secrets.io/v1beta1" }}
kind: ExternalSecret
metadata:
  name: {{ (.Values.externalSecrets.name | default (printf "%s-external-secret" .Release.Name)) }}
  namespace: {{ include "namespace" . }}
  labels:
  {{- include "labelsOther" . | nindent 4 }}
  {{- if .Values.externalSecrets.labels }}
    {{- toYaml .Values.externalSecrets.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.externalSecrets.annotations }}
  annotations:
    {{- toYaml .Values.externalSecrets.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .Values.externalSecrets.spec | nindent 2 }}
{{- end -}}
{{/*
*/}}
