{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (.Values.serviceAccount.name | default (printf "%s-sa" .Release.Name)) }}
  namespace: {{ include "namespace" . }}
  {{- if .Values.serviceAccount.labels }}
  labels:
    {{- toYaml .Values.serviceAccount.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default "false" }}
{{- end -}}
{{/*
*/}}
