{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name | default (printf "%s-monitor" .Release.Name) }}
  namespace: {{ include "namespace" . }}
  labels:
  {{- include "labelsOther" . | nindent 4 }}
  {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  jobLabel: app
  selector:
    matchLabels:
      {{- required "matchLabels for serviceMonitor is required." .Values.serviceMonitor.matchLabels | toYaml | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ default .Release.Namespace .Values.serviceMonitor.namespaceSelector }}
  endpoints:
    - port: {{ default "engine-metrics" .Values.serviceMonitor.port | quote }}
      path: {{ default "/metrics" .Values.serviceMonitor.path }}
      honorLabels: {{ default true .Values.serviceMonitor.honorLabels }}
      interval: {{ default "15s" .Values.serviceMonitor.interval }}
{{- end }}
{{/*
*/}}
