apiVersion: v2
appVersion: 0.1.0
dependencies:
- condition: prometheusServer.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.*
- condition: openCost.enabled
  name: opencost
  repository: https://opencost.github.io/opencost-helm-chart
  version: 1.*
name: c8r-opencost
sources:
- https://github.com/prometheus-community/helm-charts
- https://github.com/grafana/helm-charts
- https://opencost.github.io/opencost-helm-chart
type: application
version: 0.1.0
