apiVersion: v2
name: c8r-network-agent
description: A Helm chart for deploying c8r-network-agent on Kubernetes for network traffic monitoring
type: application
version: 0.1.1-alpha
appVersion: "v0.1.1-alpha"

keywords:
  - network
  - monitoring
  - kubernetes
  - conntrack
  - observability
  - traffic
  - daemonset

maintainers:
  - name: c8r-network-agent maintainers

annotations:
  category: Monitoring
