apiVersion: v1
kind: Secret
metadata:
  name: bearertoken
  labels: {{ include "c8r-labels" . | nindent 4 }}
  namespace: {{ include "c8r-namespace" . }}  
type: kubernetes.io/generic
stringData:
  token: {{ include "bearerToken" . | quote }}
