{{- if and .Values.rbac.create .Values.rbac.useClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.rbac.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "chart.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if .Values.rbac.useExistingRole }}
  name: {{ .Values.rbac.useExistingRole }}
{{- else }}
  name: {{ include "chart.name" . }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ default "c8r-agent-sa" .Values.serviceAccount.name }}
  namespace: {{ include "c8rAgent.namespace" . }}
{{- end -}}
