apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-config
  namespace: {{ include "c8rAgent.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  .secret-file.yml: Z2xvYmFsOgogIGV2YWx1YXRpb25faW50ZXJ2YWw6IDFtCiAgc2NyYXBlX2ludGVydmFsOiAxbQogIHNjcmFwZV90aW1lb3V0OiAxMHMKcnVsZV9maWxlczoKLSAvZXRjL2NvbmZpZy9yZWNvcmRpbmdfcnVsZXMueW1sCi0gL2V0Yy9jb25maWcvYWxlcnRpbmdfcnVsZXMueW1sCi0gL2V0Yy9jb25maWcvcnVsZXMKLSAvZXRjL2NvbmZpZy9hbGVydHMKc2NyYXBlX2NvbmZpZ3M6Ci0gam9iX25hbWU6ICdjOHIta3ViZS1zdGF0ZS1tZXRyaWNzJwogIHN0YXRpY19jb25maWdzOgogICAgLSB0YXJnZXRzOiBbJ2xvY2FsaG9zdDo4MDgwJ10KCi0gam9iX25hbWU6IGM4ci1vcGVuLWNvc3QKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czogWydsb2NhbGhvc3Q6OTAwMydd
