{{- if and (eq  .Values.rbac.create true) (eq .Values.rbac.useClusterRole false) -}}
{{- range (join "," $.Values.namespaces) | split "," }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
  name: {{ include "chart.name" $ }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if (not $.Values.rbac.useExistingRole) }}
  name: {{ include "chart.name" $ }}
{{- else }}
  name: {{ include "chart.name" $ }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ default "c8r-agent-sa" $.Values.serviceAccount.name }}
  namespace: {{ include "c8rAgent.namespace" $ }}
{{- end -}}
{{- end -}}
